# Generated by Django 5.1.6 on 2025-03-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'ordering': ['date_refusal'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='controlledaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Управляемый мост'},
        ),
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Двигатель'},
        ),
        migrations.AlterModelOptions(
            name='failurenode',
            options={'verbose_name': 'Модель узла отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
        migrations.AlterModelOptions(
            name='leadingaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Ведущий мост'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['date'], 'verbose_name': 'Модель ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterModelOptions(
            name='organizationment',
            options={'verbose_name': 'Модель организации', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Модель способа восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Модель сервисная компания', 'verbose_name_plural': 'Сервисная компания'},
        ),
        migrations.AlterModelOptions(
            name='techmodel',
            options={'verbose_name': 'Модель техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Трансмиссия'},
        ),
        migrations.AlterField(
            model_name='car',
            name='controlled_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.controlledaxle', verbose_name='Управляемый мост'),
        ),
        migrations.AlterField(
            model_name='car',
            name='leading_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.leadingaxle', verbose_name='Ведущий мост'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.transmissionmodel', verbose_name='Трансмиссия'),
        ),
    ]
