# Generated by Django 5.1.6 on 2025-03-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_complaints_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlledaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модель управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модель двигателя'},
        ),
        migrations.AlterModelOptions(
            name='leadingaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модель ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисная компания'},
        ),
        migrations.AlterModelOptions(
            name='techmodel',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модель техники'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модель трансмиссии'},
        ),
    ]
